Build Linux ARM Binary:
  stage: build
  script:
  - "export PATH=\"$PATH:/opt/gcc-arm-linux-gnueabihf/bin\""
  - "/opt/qt-armhf-5.15.4-static/bin/qmake homed-zigbee.pro"
  - "make -j8"
  - "cp homed-zigbee homed-zigbee-armhf"
  artifacts:
    paths:
    - "homed-zigbee-armhf"
    expire_in: 1 day
  except:
    - branches
  only:
    - tags

Build OpenWRT MIPS Binary:
  stage: build
  script:
  - "export PATH=\"$PATH:/opt/gcc-mips-openwrt-linux/bin\""
  - "export STAGING_DIR=\"/opt/gcc-mips-openwrt-linux\""
  - "/opt/qt-mips-5.15.4-static/bin/qmake homed-zigbee.pro"
  - "make -j8"
  - "cp homed-zigbee homed-zigbee-mips"
  artifacts:
    paths:
    - "homed-zigbee-mips"
    expire_in: 1 day
  except:
    - branches
  only:
    - tags

Deploy Linux ARM Package:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-zigbee_${CI_COMMIT_TAG}_armhf.deb
  script:
  - "mkdir -p package/data/lib/systemd/system"
  - "mkdir -p package/data/usr/local/bin"
  - "cp -r package/debian package/data/DEBIAN"
  - "cp package/systemd/homed-zigbee.service package/data/lib/systemd/system"
  - "cp homed-zigbee-armhf package/data/usr/local/bin/homed-zigbee"
  - "md5deep -lr package/data | grep -v DEBIAN | sed \"s+package/data/++g\" | sort -k2 > package/data/DEBIAN/md5sums"
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" package/data/DEBIAN/control"
  - "chmod +x package/data/DEBIAN/postinst"
  - "chmod +x package/data/DEBIAN/prerm"
  - "fakeroot dpkg-deb --build package/data"
  - "mv package/data.deb ${PACKAGE_FILE}"
  - "reprepro -b /var/lib/apt -C main includedeb debian ${PACKAGE_FILE}"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  except:
    - branches
  only:
    - tags

Deploy OpenWRT MIPS Package:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-zigbee_${CI_COMMIT_TAG}_mips_24kc.ipk
  script:
  - "mkdir -p package/data/etc/init.d"
  - "mkdir -p package/data/usr/bin"
  - "mkdir -p package/data/var/db"
  - "cp package/procd/homed-zigbee package/data/etc/init.d"
  - "cp homed-zigbee-mips package/data/usr/bin/homed-zigbee"
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" package/openwrt/control"
  - "echo \"2.0\" > debian-binary"
  - "chmod +x package/data/etc/init.d/homed-zigbee"
  - "chmod +x package/openwrt/postinst"
  - "chmod +x package/openwrt/prerm"
  - "fakeroot tar -czf control.tar.gz -C package/openwrt ."
  - "fakeroot tar -czf data.tar.gz -C package/data ."
  - "fakeroot tar -czf ${PACKAGE_FILE} control.tar.gz data.tar.gz  debian-binary"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  except:
    - branches
  only:
    - tags
