.build:
  stage: build
  script:
  - "export PATH=\"$PATH:/opt/${COMPILER}/bin\""
  - "export STAGING_DIR=\"/opt/${COMPILER}\""
  - "/opt/${QT_BUILD}/bin/qmake homed-zigbee.pro"
  - "make -j8"
  - "cp homed-zigbee homed-zigbee-${ARCHITECTURE}"
  artifacts:
    paths:
    - "homed-zigbee-${ARCHITECTURE}"
    expire_in: 1 day
  except:
    - branches
  only:
    - /^\d.\d.\d+$/

.deploy_apt:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-zigbee_${CI_COMMIT_TAG}_${ARCHITECTURE}.deb
  script:
  - "mkdir -p package/data/lib/systemd/system"
  - "mkdir -p package/data/usr/local/bin"
  - "cp -r package/debian package/data/DEBIAN"
  - "cp package/systemd/homed-zigbee.service package/data/lib/systemd/system"
  - "cp homed-zigbee-${ARCHITECTURE} package/data/usr/local/bin/homed-zigbee"
  - "md5deep -lr package/data | grep -v DEBIAN | sed \"s+package/data/++g\" | sort -k2 > package/data/DEBIAN/md5sums"
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" package/data/DEBIAN/control"
  - "sed -i \"s+^Architecture:.*+Architecture: ${ARCHITECTURE}+g\" package/data/DEBIAN/control"
  - "chmod +x package/data/DEBIAN/postinst"
  - "chmod +x package/data/DEBIAN/prerm"
  - "fakeroot dpkg-deb --build package/data"
  - "mv package/data.deb ${PACKAGE_FILE}"
  - "reprepro -b /var/lib/apt -C main includedeb debian ${PACKAGE_FILE}"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  except:
    - branches
  only:
    - /^\d.\d.\d+$/

.deploy_ipk:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-zigbee_${CI_COMMIT_TAG}_${ARCHITECTURE}.ipk
  script:
  - "mkdir -p package/data/etc/init.d"
  - "mkdir -p package/data/usr/bin"
  - "mkdir -p package/data/var/db"
  - "cp package/procd/homed-zigbee package/data/etc/init.d"
  - "cp homed-zigbee-${ARCHITECTURE} package/data/usr/bin/homed-zigbee"
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" package/openwrt/control"
  - "echo \"2.0\" > debian-binary"
  - "chmod +x package/data/etc/init.d/homed-zigbee"
  - "chmod +x package/openwrt/postinst"
  - "chmod +x package/openwrt/prerm"
  - "fakeroot tar -czf control.tar.gz -C package/openwrt ."
  - "fakeroot tar -czf data.tar.gz -C package/data ."
  - "fakeroot tar -czf ${PACKAGE_FILE} control.tar.gz data.tar.gz  debian-binary"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  except:
    - branches
  only:
    - /^\d.\d.\d+$/

Build Linux Binary (aarch64):
  extends: .build
  variables:
    COMPILER: gcc-aarch64-linux-gnu
    QT_BUILD: qt-aarch64-5.15.4-static
    ARCHITECTURE: aarch64

Build Linux Binary (armhf):
  extends: .build
  variables:
    COMPILER: gcc-arm-linux-gnueabihf
    QT_BUILD: qt-armhf-5.15.4-static
    ARCHITECTURE: armhf

Build OpenWRT Binary (mips):
  extends: .build
  variables:
    COMPILER: gcc-mips-openwrt-linux
    QT_BUILD: qt-mips-5.15.4-static
    ARCHITECTURE: mips_24kc

Deploy APT Package (aarch64):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: aarch64

Deploy APT Package (armhf):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: armhf

Deploy OpenWRT Package (mips):
  extends: .deploy_ipk
  variables:
    ARCHITECTURE: mips_24kc
